AppBundle\Entity\Years:
    type: entity
    table: Years
    indexes:
        fk_model_id:
            columns:
                - model_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        year:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        modelId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: model_id
    lifecycleCallbacks: {  }
